### ISSUE TITLE
How can I open BalloonEditor toolbar on click

### ISSUE THREAD

**Issue by SergeyKhval** [ckeditor/ckeditor5-editor-balloon#11]
I am trying to do something like this 
```javascript
const balloonEditor = BalloonEditor.create(domElement)
const toolbar = balloonEditor.plugins.get('ContextualToolbar')

balloonEditor.ui.focusTracker.on('change:isFocused', (evt, name, isFocused) => {
  if (isFocused) {
    toolbar.show()
  } else {
    toolbar.hide()
  }
})
```

However after the toolbar opens `change:range` event is fired with `selection.isCollapsed === true` and the toolbar closes. So basically it just flickers. This approach works if I click two times in the same position, which obviously does not trigger `change:range`. Is there any workaround for this.

**Comment by oleq** [comment]
Hi,

`ContextualToolbar` has been designed to respond to the selection (range) changes in a certain way. It shows up when the selection is not collapsed. 

If I got it right, what you expect is something different: a toolbar which stays attached to the caret as long as the editor stays focused. I'm afraid there's no easy way to do that unless you wish to create your own plugin, with a custom implementation of [these two privates methods](https://github.com/ckeditor/ckeditor5-ui/blob/f152dfc4e8c0cf7ad26bcb1115ffa2da92357c07/src/toolbar/contextual/contextualtoolbar.js#L105-L152).

**Comment by SergeyKhval** [comment]
Thanks, I have really managed to achieve the desired behavior by extending `ContextualToolbar` and overriding those 2 methods. However in the end I just switched to `InlineEditor` which works as I want right out of the box.
